enum KpiType {
    BLOCK_HEIGHT = 1,
    BONDED_TOKEN,
    VALIDATORS,
    BLOCK_TIME,
    INFLATION,
    TOTAL_REVIEWS,
    MERCHANTS,
    REWARDS,
    REWARDS_TODAY,
    REWARD_AVERAGE,
    BEST_REWARD_EVER,
}

export default KpiType;
